### ISSUE TITLE
Implement MediaPlayer2 interface

### ISSUE THREAD

**Issue by Mange** [Mange/mpris-rs#19]
[MediaPlayer2 interface](https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html) consists of:

- [x] Raise / CanRaise(added in 2.0)
- [x] Quit / CanQuit (added in 2.0)
- [x] Fullscreen (added in 2.0)
- [x] HasTrackList (is this even useful without implementing the `TrackList` interface?) (added in 2.0)
- [x] Identity (added in 0.1)
- [x] DesktopEntry (added in 2.0)
- [x] SupportedUriSchemes (added in 2.0)
- [x] SupportedMimeTypes (added in 2.0)

Some players will not support fullscreen at all as it was added in MPRIS 2.2, so make sure to handle its absense gracefully.
