### ISSUE TITLE
Implement TrackList interface

### ISSUE THREAD

**Issue by Mange** [Mange/mpris-rs#27]
Most of [the `TrackList` interface][interface] must be implemented to get `Player::set_position` (#26) possible to use in practice. This tracking issue is for all of that interface.

**Methods**
- [x] `GetTracksMetadata` - #39 
- [x] `AddTrack` - #43 
- [x] `RemoveTrack` - #43 
- [x] `GoTo` - #43 

**Signals**
- [x] `TrackListReplaced` - #39 
- [x] `TrackAdded` - #39 
- [x] `TrackRemoved` - #39 
- [x] `TrackMetadataChanged` - #39 

**Properties**
- [x] `Tracks` (Required for `Player::set_position`) - #39 
- [x] `CanEditTracks` - #39 

**Types**
- [x] `TrackID` (#26)
- [x] `Uri` (use normal strings)
- [x] `Metadata_Map` (done for `Player::get_metadata` in 0.1)

[interface]: https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html

**Comment by ssokolow** [comment]
While I'm glad to see that this is implemented, it turns out it's less useful than I thought because it seems like "Expose everything but TrackList via MPRIS 2.x, and then expose everything including TrackList via either [MPRIS 1.x](https://github.com/xmms2/wiki/wiki/MPRIS) (QMMP) or a non-standard D-Bus API (Audacious Media Player)" is a thing various media players do.

I guess I'll have to stick with what I'd been planning before, where I use mpris-rs to find the player, then hand off to dbus-rs to call what I now know to be the MPRIS 1.x version of AddTrack if no MPRIS 2.x version is available. (Which'll be a pain. It was bothersome enough doing runtime D-Bus introspection in Python where an XML parser is part of the standard library and the language is highly dynamic.)

(In case you're wondering, I'm working to rewrite [this](https://github.com/ssokolow/lap/) in Rust as a way to get some practice while I also bring the code quality up to my modern standards.)

**Comment by Mange** [comment]
Yeah, support for MPRIS2 seems spotty at best. I'd love to get some help supporting that version too if you're up for it.

I could also add an API that consumes a Player and gives back the underlying connection if that would help.

**Comment by ssokolow** [comment]
> Yeah, support for MPRIS2 seems spotty at best. I'd love to get some help supporting that version too if you're up for it.

Have you written any developer documentation on how the project is structured and the DOs and DON'Ts of making changes to it?

I did take a quick look at the mpris-rs source a few months ago to see how difficult it would be to implement MPRIS2 TrackList, but I walked away with a feeling that reinventing a very task-specific wheel for my own use would be quicker and easier than getting familiar with the amount of work you put into making your wheel general-purpose and future-proof. (And then something came up, which meant that I didn't even have time to do *that* until after you finished this.)

> I could also add an API that consumes a Player and gives back the underlying connection if that would help.

A way to share a `Connection` with mpris-rs in general would be nice. I imagine that, as an alternative to opening two D-Bus connections from a single application, it would be quite inefficient to have to destroy the `Player` to extract the `Connection`, then re-create it afterward whenever I want to call a method on some other D-Bus API.

**Comment by Mange** [comment]
> > Yeah, support for MPRIS2 seems spotty at best. I'd love to get some help supporting that version too if you're up for it.
> 
> Have you written any developer documentation on how the project is structured and the DOs and DON'Ts of making changes to it?

I'm not sure what exactly you'd want out of this and how it would look like. Do you know of any examples of such a document you could show me?

> 
> I did take a quick look at the mpris-rs source a few months ago to see how difficult it would be to implement MPRIS2 TrackList, but I walked away with a feeling that reinventing a very task-specific wheel for my own use would be quicker and easier than getting familiar with the amount of work you put into making your wheel general-purpose and future-proof. (And then something came up, which meant that I didn't even have time to do _that_ until after you finished this.)
> 

It's usually a very good idea to start with a less generic thing (then you have a usecase in mind), and then you extract the generic stuff when you've seen what works and what doesn't.

You could start this implementation on your own and when you have a working version, maybe a PR could be opened to this library to add the same features.

> A way to share a `Connection` with mpris-rs in general would be nice. I imagine that, as an alternative to opening two D-Bus connections from a single application, it would be quite inefficient to have to destroy the `Player` to extract the `Connection`, then re-create it afterward whenever I want to call a method on some other D-Bus API.

Hmm, but then again sharing is not easy in Rust, especially not between two different libraries. This library also needs to set up some subscriptions on the connection, so it really wants to own it so the subscriptions are exclusive to my own "event loop", and that the subscriptions can be cleaned up.

On the macro scale, I don't think having two connections to the bus would be a performance issue. Unless it's a major hassle to have multiple connections, I'd rather not spend all the time needed to come up with a way to share the connections.

However, PRs are always welcome. If you can come up with a working idea, then I would look at it and potentially merge/implement it.

**Comment by ssokolow** [comment]
> I'm not sure what exactly you'd want out of this and how it would look like. Do you know of any examples of such a document you could show me?

I'll have to think about where I last saw such a document, but the basic problem is that, when I look at your code, I don't know...

1. ...what the overall architecture is (ie. Why code is organized the way it is, how the call graph is laid out and why you chose that, etc.)
2. ...what the preferred workflow for extending it is. (ie. A simple, high-level description of the steps you'd go through to add new interfaces, how thorough any automated tests should be, and what you'd do to get them into a state you feel is ready for release.)
3. ...how things like `generate-mpris-interface.sh` fit into the workflow. (Whenever I see evidence that code generation is taking place and I don't see a clear explanation of which files should and should not be hand-edited, that risk alone can be demotivating enough to drive me off.)
4. ...any caveats that might not be obvious to a newcomer which you discovered/verified through experience while developing the project. (eg. Your rationale for not allowing the D-Bus connection to be shared would fall under this heading.)

Good "developer documentation" generally means a combination of the following:

1. Reliable instructions for how to set up a development environment and perform common development tasks. (ie. Which FFI or tool dependencies must be manually installed and how to build, trigger test runs, run examples, etc. For example, confirming the correctness of `cargo build`, `cargo run`, and `cargo test` vs. informing contributors that a proper build needs to be run as `just build` or `cargo make build` or something like that.)
2. High-quality API documentation (ie. Good use of doc comments so `cargo doc` output is as helpful as possible.)
3. Answers to the high-level questions I gave earlier (ie. Stuff to help answer questions like "If I want to add code which does X, which module is the most appropriate place for it?" or "Which files (if any) should not be hand-edited?")

Basically, answers to three questions: "How do I make this build properly?", "What is it like inside?", and "**Why** is it like this inside?"

It's that "why" that projects are most likely to neglect since it's too abstract for things like `cargo doc` to provide a template for people to fill in.

> It's usually a very good idea to start with a less generic thing (then you have a usecase in mind), and then you extract the generic stuff when you've seen what works and what doesn't.
> 
> You could start this implementation on your own and when you have a working version, maybe a PR could be opened to this library to add the same features.

Except that I came in with that intent in mind, but got scared off by the presence of `generate-mpris-interface.sh` combined with the absence of developer documentation explaining what it means for me as a developer.

That's an example of what I meant by "the amount of work you put into making your wheel general-purpose and future-proof".

> On the macro scale, I don't think having two connections to the bus would be a performance issue. Unless it's a major hassle to have multiple connections, I'd rather not spend all the time needed to come up with a way to share the connections.

Fair enough. It just seems really ugly and unidiomatic to have one program opening more than one connection to a given service just because different libraries can't share. It's bad enough that some of my Python projects have to open two connections because there's no cross-desktop standard for global hotkeys, GTK+ bindings don't have `XGrabKey`, and X11 bindings like `python-xlib`, `xpyb` and `xcffib` can't share a single connection with the GTK+ bindings.

**Comment by Mange** [comment]
That's a shame. I might write something like that later.

The generation script only touches the module named `generated`. I usually try to make the structure as obvious as possible without external documents. This script is only needed when the dbus crate makes changes, which is not obvious from reading the source code. This is something that I should document somewhere.
